name: Deploy to Heroku

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Set up Python 3.10
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=venv
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=venv

    # Authenticate Heroku CLI using API key
    - name: Authenticate Heroku CLI
      run: |
        echo $HEROKU_API_KEY | heroku auth:token
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    # Deploy to Heroku
    - name: Deploy to Heroku
      run: |
        heroku git:remote -a scrapemaster
        git push heroku master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
