name: Deploy to Heroku

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Set up Python 3.10
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    # Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run flake8 linting
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Run tests with pytest
    - name: Test with pytest
      run: |
        pytest

    # Deploy to Heroku
    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Store this as a GitHub secret
      run: |
        git remote add heroku https://git.heroku.com/your-heroku-app-name.git
        git push heroku master
